services:
  - type: web
    name: maxpremier-backend
    env: node
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false

